server:
  port: 8006

spring:
  application:
    name: springcloud-providerconsul-payment

#  consul的注册地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}