server:
  port: 8001

spring:
  application:
    name: springcloud-payment-hystrix-service

eureka:
  client:
#    表示将当前的服务注册到注册中心eureka去
    register-with-eureka: true
#    表示是否从EurekaServer中抓取已有的注册信息，默认为true，单节点表为所谓
    fetch-registry: true
#    表示将该微服务注册到具体的哪个注册中心里面
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/