server:
  port: 2001

spring:
  application:
    name: seata-order-service

  cloud:
#    nacos注册中心
    nacos:
      discovery:
        server-addr: localhost:8848

#     分布式事务的处理
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的file.conf文件意义对应
        tx-service-group: fsp_tx_group

# 与数据库进行连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:


#OpenFeign
feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath*:mapper/*.xml
