server:
  port: 8401

spring:
  application:
    name: sentinel-nacos-service

  cloud:
#   nacos注册中心
    nacos:
      discovery:
        # 将当前的微服务 sentinel-nacos-service 注册到注册中心 8848 里面
        server-addr: localhost:8848  # nacos的服务注册中心地址

#   sentinel监控中心
    sentinel:
      transport:
        # 使用监控中心 8080 来监控当前的微服务 couldalibaba-sentinel-service
        dashboard: localhost:8080   # 配置sentinel的地址
        # 默认的端口号是8719，假如被占用则会自动的在 端口号的上面进行 +1 扫描
        # 直到找到未被占用的端口号
        port: 8719

# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
