server:
  port: 80

#不将其注册进入eureka注册中心里面
#spring:
#  application:
#    name: springcloud-consumer-order

eureka:
  client:  # 表示当前为Client，客户端
    register-with-eureka: false  # 表示是否将自己注册到EurekaServer默认为true
    service-url:
      # 集群版，即要将所有的服务都要注册到eureka注册中心里面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


# 打印指定接口的详细的详细的日记功能
logging:
  level:
    com.liu.springcloud.service.PaymentFeignService: debug