server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://localhost:3306/seata_account
    username: root
    password:

# 不是用hystrix作为注册中心
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

#映射文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
